networks:
  internal:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${CONTAINER_NAME}-nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - "8088:80"
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./src/wp-content/plugins/${PLUGIN_NAME}:/var/www/html/wp-content/plugins/${PLUGIN_NAME}:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - internal

  database:
    image: mysql:latest
    container_name: ${CONTAINER_NAME}-mysql
    restart: unless-stopped
    env_file: .env
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVICE_TAG=dev
      - SERVICE_NAME=mysql
    networks:
      - internal

  wordpress:
    depends_on:
      - database
    container_name: ${CONTAINER_NAME}-wordpress
    image: wordpress:6.5.2-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306 
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./wordpress:/var/www/html:delegated
      - ./src/wp-content/plugins/${PLUGIN_NAME}:/var/www/html/wp-content/plugins/${PLUGIN_NAME}:delegated
    networks:
      - internal

  composer:
    image: composer:latest
    container_name: ${CONTAINER_NAME}-composer
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - ./src/wp-content/plugins/${PLUGIN_NAME}:/app:delegated
      - ./wordpress:/var/www/html:delegated
    working_dir: /app
    networks:
      - internal