networks:
  internal:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${CONTAINER_NAME}-nginx
    env_file: .env
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
      - database
    networks:
      - internal

  database:
    image: mysql:latest
    container_name: ${CONTAINER_NAME}-mysql
    restart: unless-stopped
    env_file: .env
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVICE_TAG=dev
      - SERVICE_NAME=mysql
    networks:
      - internal

  php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: ${CONTAINER_NAME}-php
    env_file: .env
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - internal

  phpmyadmin:
    container_name: ${CONTAINER_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "8081:80"
    networks:
      - internal
